alias: Living Room Plant alert on
trigger:
  - platform: numeric_state
    entity_id: sensor.living_room_plant_moisture
    below: 15
action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.alert_living_room_plant