alias: "Home for 8 minutes"
trigger:
  - platform: state
    entity_id: group.all_devices
    to: 'home'
    for:
      minutes: 8
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.just_returned_home