alias: "Washing Machine Finished Cycle - Notify Brett"
trigger:
 - platform: state
   entity_id: input_select.washer
   to: 'Clean'
condition:
  - condition: state
    entity_id: input_select.washer_user
    state: 'Brett'
action:
  - service: notify.sms
    data:
      message: "Your clothes are done being washed."
      target:
        - !secret SMS_BRETT