alias: "Toogle Pasta Part Reminder On"
trigger:
  platform: mqtt
  topic: reminder/pasta_part
  payload: "active"
condition:
  - condition: state
    entity_id: input_boolean.alert_pasta_part
    state: 'off'
action:
  - service: timer.start
    entity_id: timer.pasta_part