homeassistant:
  name: Bulock Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Detroit
  customize_glob:
    "*.*":
      custom_ui_state_card: state-card-custom-ui
    "light.*":
      state_card_mode: break-slider-toggle
  customize: !include_dir_merge_named customizations

http:
  api_password: !secret password
  use_x_forwarded_for: True
  trusted_networks: 10.0.0.0/22
  ip_ban_enabled: True
  login_attempts_threshold: 10

sun:
updater:
frontend:
  javascript_version: latest
conversation:
zeroconf:
alexa:
map:
config:

history:
logbook:
recorder:
  db_url: !secret db_path
  purge_interval: 7
  purge_keep_days: 30
influxdb:
  host: app

alert: !include_dir_merge_named alerts
automation: !include_dir_list automation
binary_sensor: !include_dir_merge_list binary_sensors
camera: !include_dir_merge_list cameras
device_tracker: !include device_tracker.yaml
google_assistant: !include google_assistant.yaml
group: !include_dir_named groups
input_boolean: !include input_boolean.yaml
input_select: !include_dir_merge_named input_selects
intent_script: !include_dir_merge_named intent_scripts
media_player: !include_dir_merge_list media_players
notify: !include notify.yaml
plant: !include_dir_merge_named plants
scene: !include_dir_merge_list scenes
script: !include_dir_named scripts
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
weblink: !include weblink.yaml
wink: !include wink.yaml
xiaomi_aqara: !include xiaomi_aqara.yaml
zone: !include_dir_merge_list zones

mqtt:
  broker: mqtt
  client_id: home-assistant

ecobee:
  api_key: !secret ecobee_key

light:
  - platform: osramlightify
    host: osram
  - platform: mqtt
    name: "Christmas Tree Lights"
    state_topic: "home/lights/christmastree/POWER"
    command_topic: "home/lights/christmastree/cmnd/Power1"
    availability_topic: "home/lights/christmastree/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true

#caseta:
lutron_caseta_pro:
  bridges:
    - host: lutron

twilio:
  account_sid: !secret TWILIO_SID
  auth_token: !secret TWILIO_TOKEN

ring:
  username: !secret ring_user
  password: !secret ring_pass

octoprint:
  host: 3dprinter
  api_key: !secret octoprint_key

tts:
  - platform: google

customizer:
  custom_ui: local

zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 20000
  network_key: !secret zwave_network_key
  config_path: /usr/local/lib/python3.4/dist-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
