homeassistant:
  name: Bulock Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Detroit
  customize: !include_dir_merge_named customizations

http:
  api_password: !secret password
  use_x_forwarded_for: True
  trusted_networks: 10.0.0.0/8

discovery:
sun:
updater:
frontend:
conversation:
zeroconf:

history:
logbook:
recorder:
  db_url: !secret db_path
influxdb:
  host: app

binary_sensor: !include_dir_merge_list binary_sensors
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
group: !include_dir_named groups
zone: !include_dir_merge_list zones
scene: !include_dir_merge_list scenes
automation: !include_dir_list automation
notify: !include notify.yaml
cover: !include cover.yaml
wink: !include wink.yaml
weblink: !include weblink.yaml
device_tracker: !include device_tracker.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
shell_command: !include shell_command.yaml
alexa:
  intents: !include_dir_merge_named alexa


mqtt:
  broker: mqtt
  client_id: home-assistant

nest:
  client_id: !secret nest_client
  client_secret: !secret nest_secret

climate:
  platform: nest

light:
  platform: osramlightify
  host: osram

lutron_caseta:
  host: lutron

twilio:
  account_sid: !secret TWILIO_SID
  auth_token: !secret TWILIO_TOKEN

ring:
  username: !secret ring_user
  password: !secret ring_pass

camera:
  platform: generic
  still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=GRR&brand=wui&num=1&delay=15&type=N0R&frame=0&scale=0.75&noclutter=1&showstorms=99&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=1&lightning=1&smooth=1&rand=24702900&lat=0&lon=0&label=you
  name: Radar

zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 20000
  config_path: /usr/local/lib/python3.4/dist-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config

#custom components
battery_state:
