homeassistant:
  name: Bulock Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Detroit
  customize: !include_dir_merge_named customizations

http:
  api_password: !secret password
  use_x_forwarded_for: True
  trusted_networks: 10.0.0.0/8

discovery:
sun:
updater:
frontend:
conversation:
zeroconf:

history:
logbook:
recorder:
  db_url: !secret db_path
influxdb:
  host: app

binary_sensor: !include_dir_merge_list binary_sensors
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
group: !include_dir_named groups
zone: !include_dir_merge_list zones
scene: !include_dir_merge_list scenes
automation: !include_dir_list automation
alert: !include_dir_merge_named alerts
notify: !include notify.yaml
cover: !include cover.yaml
wink: !include wink.yaml
weblink: !include weblink.yaml
device_tracker: !include device_tracker.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
shell_command: !include shell_command.yaml
camera: !include_dir_merge_list cameras
alexa:
  intents: !include_dir_merge_named alexa

mqtt:
  broker: mqtt
  client_id: home-assistant

ecobee:
  api_key: !secret ecobee_key

light:
  platform: osramlightify
  host: osram

lutron_caseta:
  host: lutron

twilio:
  account_sid: !secret TWILIO_SID
  auth_token: !secret TWILIO_TOKEN

ring:
  username: !secret ring_user
  password: !secret ring_pass

octoprint:
  host: 3dprinter
  api_key: !secret octoprint_key

media_player:
  - platform: vizio
    name: Living Room TV
    host: living.chromecast
    access_token: !secret vizio_key

zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 20000
  config_path: /usr/local/lib/python3.4/dist-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
  new_entity_ids: true
