homeassistant:
  name: Bulock Home
  latitude: [REDACTED]
  longitude: [REDACTED]
  temperature_unit: F
  time_zone: America/Detroit
  customize: !include customize.yaml

discovery:
sun:
updater:
frontend:
conversation:
logbook:
history:
sensor: !include sensor.yaml
group: !include group.yaml
zone: !include zone.yaml
scene: !include scene.yaml
automation: !include automation.yaml
script: !include script.yaml
weblink: !include weblink.yaml

http:
  api_password: [REDACTED]

device_tracker:
  platform: unifi
  host: 10.10.200.103
  port: 8443
  username: admin
  password: [REDACTED]
  track_new_devices: no
  interval_seconds: 30

wink:
  access_token: [REDACTED]
  refresh_token: [REDACTED]

notify:
  platform: pushbullet
  api_key: [REDACTED]

nest:
  username: [REDACTED]
  password: [REDACTED]

thermostat:
  platform: nest
