homeassistant:
  name: Bulock Home
  latitude: !secret HA_HOME_LATITUDE
  longitude: !secret HA_HOME_LONGITUDE
  elevation: !secret HA_HOME_ELEVATION
  unit_system: imperial
  time_zone: America/Detroit
  customize: !include_dir_merge_named customizations

http:
  cors_allowed_origins:
      - https://dashboard.local.bulock.com

discovery:
sun:
updater:
frontend:
conversation:
logbook:
history:
zeroconf:

sensor: !include_dir_merge_list sensors
group: !include_dir_named groups
zone: !include_dir_merge_list zones
scene: !include_dir_merge_list scenes
automation: !include_dir_list automation
notify: !include notify.yaml
weblink: !include weblink.yaml
device_tracker: !include device_tracker.yaml
input_select: !include input_select.yaml
panel_iframe: !include_dir_named panels

emulated_hue:
  exposed_domains:
    - switch
    - light

mqtt:
  broker: localhost
  client_id: home-assistant

wink:
  access_token: !secret HA_WINK_ACCESS

nest:
  username: !secret HA_NEST_USER
  password: !secret HA_NEST_PW

climate:
  platform: nest

garage_door:
  platform: myq
  name: Garage Door
  username: !secret MYQ_USER
  password: !secret MYQ_PW

zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 2000
  config_path: /usr/local/lib/python3.4/dist-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
