homeassistant:
  name: Bulock Home
  latitude: !env_var HA_HOME_LATITUDE
  longitude: !env_var HA_HOME_LONGITUDE
  temperature_unit: F
  time_zone: America/Detroit
  customize: !include_dir_merge_named customizations

http:
discovery:
sun:
updater:
frontend:
conversation:
logbook:
history:
zeroconf:

sensor: !include_dir_merge_list sensors
group: !include_dir_named groups
zone: !include_dir_merge_list zones
scene: !include_dir_merge_list scenes
automation: !include_dir_list automation
notify: !include notify.yaml
weblink: !include weblink.yaml
device_tracker: !include device_tracker.yaml

mqtt:
  broker: localhost
  client_id: home-assistant

wink:
  access_token: !env_var HA_WINK_ACCESS
  refresh_token: !env_var HA_WINK_REFRESH

nest:
  username: !env_var HA_NEST_USER
  password: !env_var HA_NEST_PW

thermostat:
  platform: nest

zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 2000
  config_path: /usr/local/lib/python3.4/dist-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config