homeassistant:
  name: Bulock Home
  latitude: !env_var HA_HOME_LATITUDE
  longitude: !env_var HA_HOME_LONGITUDE
  temperature_unit: F
  time_zone: America/Detroit
  customize: !include customize.yaml

http:
discovery:
sun:
updater:
frontend:
conversation:
logbook:
history:
zeroconf:
sensor: !include sensor.yaml
group: !include group.yaml
zone: !include zone.yaml
scene: !include scene.yaml
automation: !include_dir_list automation
script: !include script.yaml
notify: !include notify.yaml
weblink: !include weblink.yaml

device_tracker:
  platform: unifi
  host: unifi
  port: 8443
  username: admin
  password: !env_var HA_UNIFI_PW
  track_new_devices: no
  interval_seconds: 30

wink:
  access_token: !env_var HA_WINK_ACCESS
  refresh_token: !env_var HA_WINK_REFRESH

nest:
  username: !env_var HA_NEST_USER
  password: !env_var HA_NEST_PW

thermostat:
  platform: nest
