alias: "Set thermostat to away when away"
trigger:
  - platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
action:
    - service: climate.set_away_mode
      data:
        entity_id: climate.main_floor
        away_mode: true
