alias: "Turn off Master Bathroom Light"
trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d0001e50edf
    to: 'off'
    for:
      minutes: 20
condition:
  - condition: numeric_state
    entity_id: sensor.master_bathroom_humidity_diff
    below: 15
action:
  - service: light.turn_off
    entity_id: light.master_bathroom_light
