alias: "Outdoor Lights On at Dark"
trigger:
  - platform: sun
    event: sunset
    offset: '-00:10:00'
condition:
  - condition: state
    entity_id: light.front_porch
    state: 'off'
action:
    service: scene.turn_on
    data_template:
      entity_id: scene.outdoors_{{ states.input_select.outdoor_lights.state | lower | replace(' ', '_') | replace('\'', '') }}
