alias: Set humidity - 10 - 0 degrees
trigger:
  - platform: numeric_state
    entity_id: sensor.dark_sky_temperature
    below: 10
    above: 0
action:
  - service: climate.set_humidity
    data:
      entity_id: climate.main_floor
      humidity: 25