alias: "Alert if Brett's plant needs water when home"
trigger:
  - platform: numeric_state
    entity_id: sensor.bretts_plant_moisture
    below: 20
condition:
  - condition: state
    entity_id: device_tracker.brett
    state: 'home'
action:
  - service: notify.sms
    data:
      message: "Your plant needs to be watered."
      target:
        - !secret SMS_BRETT