alias: "Outdoor Light Switch Off"
trigger:
  - platform: template
    value_template: "{{ is_state_attr('binary_sensor.outdoor_light_switch', 'button_off_pressed', true) }}"
action:
  - service: scene.turn_on
    entity_id: scene.outdoors_off