alias: "Turn off long running fireplace"
trigger:
  - platform: state
    entity_id: switch.fireplace_switch
    to: 'on'
    for:
      hours: 4
action:
  - service: switch.turn_off
    entity_id: switch.fireplace_switch
  - service: notify.sms
    data:
      message: "Fireplace was left on, is now turned off."
      target:
        - !secret SMS_CAMERON
  - service: notify.sms
    data:
      message: "Fireplace was left on, is now turned off."
      target:
        - !secret SMS_RACHAEL