alias: "Alert if living room plant needs water"
trigger:
  - platform: numeric_state
    entity_id: sensor.living_room_plant_moisture
    below: 15
action:
  - service: notify.sms
    data:
      message: "The living room plant needs to be watered."
      target:
        - !secret SMS_CAMERON
  - service: notify.sms
    data:
      message: "The living room plant needs to be watered."
      target:
        - !secret SMS_RACHAEL