alias: "Alert if master bedroom plant needs water"
trigger:
  - platform: numeric_state
    entity_id: sensor.master_bedroom_plant_moisture
    below: 18
action:
  - service: notify.sms
    data:
      message: "The master bedroom plant needs to be watered."
      target:
        - !secret SMS_CAMERON
  - service: notify.sms
    data:
      message: "The master bedroom plant needs to be watered."
      target:
        - !secret SMS_RACHAEL