- platform: template
  sensors:
    average_temp:
      friendly_name: Average Indoor Temp
      unit_of_measurement: '°F'
      value_template: >
        {% set sensors = [
          states.sensor.breakfast_bar_temperature.state|float,
          states.sensor.bretts_plant_temperature.state|float,
          states.sensor.main_floor_temperature.state|float,
          states.sensor.upstairs_temperature.state|float,
          states.sensor.living_room_plant_temperature.state|float,
          states.sensor.master_bedroom_plant_temperature.state|float,
          states.sensor.temperature_158d0001b952f4.state|float
        ] %}

        {{ (sensors|sum / sensors|length)|round(1) }}

    downstairs_bathroom_motion_batt:
      value_template: '{{ states.zwave.downstairs_bathroom.attributes.battery_level }}'
      friendly_name: 'Downstairs Bathroom Motion'
      unit_of_measurement: '%'
    breakfast_bar_motion_batt:
      value_template: '{{ states.binary_sensor.breakfast_bar_motion.attributes.battery_level }}'
      friendly_name: 'Breakfast Bar Motion'
      unit_of_measurement: '%'
    basement_window_batt:
      value_template: '{{ states.zwave.basement_window.attributes.battery_level }}'
      friendly_name: 'Basement Window Sensor'
      unit_of_measurement: '%'
    front_door_batt:
      value_template: '{{ states.zwave.front_door_2.attributes.battery_level }}'
      friendly_name: 'Front Door Sensor'
      unit_of_measurement: '%'
    front_door_lock_batt:
      value_template: '{{ states.zwave.front_door.attributes.battery_level }}'
      friendly_name: 'Front Door Lock'
      unit_of_measurement: '%'
    rear_door_batt:
      value_template: '{{ states.zwave.rear_door.attributes.battery_level }}'
      friendly_name: 'Rear Door Sensor'
      unit_of_measurement: '%'
    siren_batt:
      value_template: '{{ states.wink.siren__strobe.attributes.battery_level }}'
      friendly_name: 'Siren'
      unit_of_measurement: '%'
    cameron_phone_batt:
      value_template: '{{ states.device_tracker.cbulock_oneplus3t.attributes.battery }}'
      friendly_name: Cameron's Phone
      unit_of_measurement: '%'
    master_bathroom_sensor_batt:
      value_template: '{{ states.sensor.humidity_158d0001b952f4.attributes.battery_level }}'
      friendly_name: 'Master Bathroom Humidity Sensor'
      unit_of_measurement: '%'
    master_bathroom_motion_batt:
      value_template: '{{ states.binary_sensor.motion_sensor_158d0001e50edf.attributes.battery_level }}'
      friendly_name: Master Bathroom Motion Sensor
      unit_of_measurement: '%'
    kids_bathroom_motion_batt:
      value_template: '{{ states.binary_sensor.motion_sensor_158d00022516f7.attributes.battery_level }}'
      friendly_name: Kid's Bathroom Motion Sensor
      unit_of_measurement: '%'

    washing_machine_status:
      value_template: '{{ states.input_select.washer.state }}'
      friendly_name: 'Status'
      icon_template: mdi:washing-machine

    master_bathroom_humidity_diff:
      value_template: '{{float(states.sensor.humidity_158d0001b952f4.state) - float(states.sensor.main_floor_humidity.state)}}'
      friendly_name: Master Bedroom Humidity Difference
      unit_of_measurement: '%'

    front_door_lock_action:
      friendly_name: 'Front Door Lock Action'
      value_template: >-
        {% if is_state('sensor.front_door_alarm_type', '18') %}
          {% if is_state('sensor.front_door_alarm_level', '0') %}
        Locked: Outside Keypad
          {% else %}
        Locked: User {{states('sensor.front_door_alarm_level')}}
          {% endif %}
        {% elif is_state('sensor.front_door_alarm_type', '19') %}
          Unlocked: User Code {{states('sensor.front_door_alarm_level')}}
        {% elif is_state('sensor.front_door_alarm_type', '21') %}
          Locked: {{[ 'Outside Lock', 'Inside Deadbolt', 'Outside Keypad' ][states('sensor.front_door_alarm_level')|int]}}
        {% elif is_state('sensor.front_door_alarm_type', '22') %}
          Unlocked: Inside Deadbolt
        {% else %}
          Unknown: {{states('sensor.front_door_alarm_type')}}/{{states('sensor.front_door_alarm_level')}}
        {% endif %}

