- platform: template
  sensors:
    indoor_temp:
      value_template: '{{ states.climate.kitchen.attributes.current_temperature }}'
      friendly_name: 'Indoor Temp'
      unit_of_measurement: '°F'
    downstairs_bathroom_motion_batt:
      value_template: '{{ states.sensor.downstairs_bathroom_motion_sensor_alarm_level_2.attributes.battery_level }}'
      friendly_name: 'Downstairs Bathroom Motion'
      unit_of_measurement: '%'
    breakfast_bar_motion_batt:
      value_template: '{{ states.binary_sensor.breakfast_bar.attributes.battery_level }}'
      friendly_name: 'Breakfast Bar Motion'
      unit_of_measurement: '%'
    basement_window_batt:
      value_template: '{{ states.binary_sensor.basement_window.attributes.battery_level }}'
      friendly_name: 'Basement Window Sensor'
      unit_of_measurement: '%'
    front_door_batt:
      value_template: '{{ states.binary_sensor.front_door.attributes.battery_level }}'
      friendly_name: 'Front Door Sensor'
      unit_of_measurement: '%'
    front_door_lock_batt:
      value_template: '{{ states.lock.front_door_lock.attributes.battery_level }}'
      friendly_name: 'Front Door Lock'
      unit_of_measurement: '%'
    rear_door_batt:
      value_template: '{{ states.binary_sensor.rear_door.attributes.battery_level }}'
      friendly_name: 'Rear Door Sensor'
      unit_of_measurement: '%'
    siren_batt:
      value_template: '{{ states.switch.siren__strobe.attributes.battery_level }}'
      friendly_name: 'Siren'
      unit_of_measurement: '%'