alias: "Brett light on at night"
trigger:
  - platform: time
    hours: 21
    minutes: 45
    seconds: 0
condition:
  - condition: time
    weekday:
      - sun
      - mon
      - tue
action:
    service: scene.turn_on
    entity_id: scene.brett_lamp_night