alias: "Living Room Light Switch Off"
trigger:
  - platform: template
    value_template: "{{ is_state_attr('binary_sensor.living_room_lamp_switch', 'button_off_pressed', true) }}"
action:
  - service: light.turn_off
    entity_id: light.living_room_lamp