alias: "Update Alert Light"
trigger:
  - platform: state
    entity_id: >
      input_boolean.alert_living_room_plant, 
      input_boolean.alert_master_bedroom_plant, 
      input_boolean.alert_bathroom_plant,
      input_boolean.alert_aloe_plant,
      input_boolean.alert_washer, 
      input_boolean.alert_front_door, 
      input_boolean.alert_back_door,
      input_boolean.alert_pasta_part,
      input_boolean.alert_roomba_full
condition:
  - condition: state
    entity_id: group.alerts
    state: 'on'
action:
  - service: script.set_alert_color
    data_template:
      id: light.gateway_light_7811dc64f587
      color: >-
        {% for alert in states.input_boolean if alert.attributes.color and alert.state == 'on' %}
          {% if loop.first %}
            {{ alert.attributes.color }}
          {% endif %}
        {% endfor %}