alias: Set humidity - 30 - 40 degrees
trigger:
  - platform: numeric_state
    entity_id: sensor.dark_sky_temperature
    below: 40
    above: 30
action:
  - service: climate.set_humidity
    data:
      entity_id: climate.main_floor
      humidity: 40