alias: Set humidity - -10 - 0 degrees
trigger:
  - platform: numeric_state
    entity_id: sensor.dark_sky_temperature
    below: 0
    above: -10
action:
  - service: climate.set_humidity
    data:
      entity_id: climate.main_floor
      humidity: 23