alias: Set humidity - -20 or below
trigger:
  - platform: numeric_state
    entity_id: sensor.dark_sky_temperature
    below: -20
action:
  - service: climate.set_humidity
    data:
      entity_id: climate.main_floor
      humidity: 10