- platform: cast
  host: living.chromecast
- platform: cast
  host: master.chromecast
- platform: cast
  host: loft.chromecast
- platform: cast
  host: basement.chromecast
- platform: cast
  host: hailey.chromecast
- platform: cast
  host: brett.chromecast
- platform: cast
  host: living.audio.chromecast
- platform: cast
  host: patio.audio.chromecast
- platform: cast
  host: downstairs.gh
- platform: cast
  host: master.gh
- platform: cast
  host: hailey.gh
- platform: cast
  host: brett.gh
- platform: cast
  host: basement.gh