alias: "Turn on Downstairs Bathroom Light Night"
trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d000222e10a
    from: 'off'
    to: 'on'
condition:
  - condition: state
    entity_id: light.downstairs_bathroom_lights
    state: 'off'
  - condition: time
    after: '22:00:00'
    before: '8:00:00'
action:
  - service: scene.turn_on
    entity_id: scene.downstairs_bathroom_night
