alias: "Ensure Garage Door Stays Closed at Night"
trigger:
  - platform: state
    entity_id: garage.door_garage_door_opener
    to: 'open'
condition:
  - condition: sun
    before: sunset
    before_offset: '-00:30:00'
action:
  - delay:
      minutes: 30
  - service: garage_door.close
    data:
      entity_id: garage_door.garage_door_opener
