alias: "Ensure Garage Door Stays Closed at Night"
trigger:
  - platform: state
    entity_id: garage.door_garage_door_opener
    to: 'open'
    for:
      minutes: 10
condition:
  - condition: sun
    after: sunset
action:
  - service: garage_door.close
    data:
      entity_id: garage_door.garage_door
