alias: "Close Garage Door Overnight"
trigger:
  - platform: sun
    event: sunset
condition:
  - condition: state
    entity_id: garage_door.garage_door_opener
    state: 'open'
action:
    service: garage_door.close
    entity_id: garage_door.garage_door_opener
