alias: "Turn on Hall Light When Arriving Home"
trigger:
  - platform: state
    entity_id: garage_door.garage_door
    from: 'closed'
    to: 'open'
condition:
  - condition: state
    entity_id: binary_sensor.breakfast_bar_motion
    state: 'off'
    for:
      minutes: 30
action:
  - service: scene.turn_on
    entity_id: scene.arrive_home