alias: "Home Asssistant Update"
trigger:
  - platform: state
    entity_id: updater.updater
action:
    service: notify.sms
    data:
      message: "New version {{ states.updater.updater.state }} of Home Assistant is available."
      target:
        - !env_var SMS_CAMERON
