alias: "Turn off Kitchen Lights Overnight"
trigger:
  - platform: state
    entity_id: binary_sensor.breakfast_bar_motion
    from: 'on'
    to: 'off'
    for:
      minutes: 5
condition:
  - condition: state
    entity_id: light.kitchen_cabinets
    state: 'on'
action:
  - service: scene.turn_on
    entity_id: scene.kitchen_off
