alias: "Loft lights off at night"
trigger:
  - platform: time
    hours: 1
    minutes: 0
    seconds: 0
condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
action:
    service: scene.turn_on
    entity_id: scene.loft_off