alias: "Loft lights on at night"
trigger:
  - platform: time
    hours: 10
    minutes: 0
    seconds: 0
condition:
  - condition: time
    weekday:
      - sun
      - mon
      - tue
action:
    service: scene.turn_on
    entity_id: scene.loft_dim