alias: "Outdoor Lights On at Dark"
trigger:
  - platform: sun
    event: sunset
    offset: '-00:10:00'
condition:
  - condition: state
    entity_id: light.front_porch
    state: 'off'
action:
    service: scene.turn_on
    entity_id: scene.outdoors_bright
