alias: "Turn off Downstairs Bathroom Light"
trigger:
  - platform: state
    entity_id: binary_sensor.downstairs_bathroom_motion_sensor_sensor_2_0
    from: 'on'
    to: 'off'
    for:
      minutes: 8
condition:
  - condition: state
    entity_id: light.downstairs_bathroom_lights
    state: 'on'
action:
  - service: light.turn_off
    entity_id: light.downstairs_bathroom_lights
