alias: "Vacuum downstairs"
trigger:
  - platform: time
    hours: 3
    minutes: 0
    seconds: 0
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - mon
        - wed
        - fri
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
action:
    service: vacuum.turn_on
    entity_id: vacuum.roomba