alias: "Washing Machine Finished Cycle"
trigger:
 - platform: state
   entity_id: sensor.washer_status
   to: 'End of cycle'
action:
  - service: notify.sms
    data:
      message: "Washing machine cycle is complete"
      target:
        - !env_var SMS_CAMERON
  - service: notify.sms
    data:
      message: "Washing machine cycle is complete"
      target:
        - !env_var SMS_RACHAEL
