alias: "Set Washer User - Brett"
trigger:
  platform: mqtt
  topic: laundry/brett
  payload: "active"
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.washer_user
      option: "Brett"