alias: "Turn on Master Bathroom Fan When Humid"
trigger:
  - platform: numeric_state
    entity_id: sensor.master_bathroom_humidity_diff
    above: 15
action:
  - service: switch.turn_on
    entity_id: switch.master_bathroom_exhaust_fan