alias: "Turn on Master Bathroom Light Night"
trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d0001e50edf
    from: 'off'
    to: 'on'
condition:
  - condition: state
    entity_id: light.master_bathroom
    state: 'off'
  - condition: time
    after: '22:00:00'
    before: '1:00:00'
action:
  - service: scene.turn_on
    entity_id: scene.master_bathroom_night